### ISSUE TITLE
what is the status??

### ISSUE THREAD

**Issue by wolverine810** [Q39-AOSP/android_device_qcom_msm8916_64#1] opened 2017-04-21 11:28 UTC

**Comment by lrinQVQ** [comment] 2017-04-21 13:40
i git push -f for add commit message.
now kernel is work,but i have something to do~ i will update kernel source tomorrow

**Comment by rvs16** [comment] 2017-04-26 05:09
Hey we are very excited about your work..!!

Can you tell me when can we expect the latest ROM for (q39).

**Comment by lrinQVQ** [comment] 2017-04-26 13:44
@rvs16 the lk have some bug orz,and because gfw i can't push commit to github QAQ

**Comment by rvs16** [comment] 2017-04-29 15:21
Does that mean you stopped developing the ROM..??

**Comment by lrinQVQ** [comment] 2017-04-29 17:13
@rvs16 no,i will developing the ROM,somethings is work

**Comment by lrinQVQ** [comment] 2017-05-03 09:33
I will update work kernel source tonight (GMT+8)

**Comment by lrinQVQ** [comment] 2017-05-03 17:02
kernel source update,and it's boot well,but touch now work @rvs16

**Comment by lrinQVQ** [comment] 2017-05-03 17:13
![qq 20170504003824](https://cloud.githubusercontent.com/assets/12861134/25672603/ded4563a-3066-11e7-9b76-0ea4b8c74d97.png)
![qq 20170504003625](https://cloud.githubusercontent.com/assets/12861134/25672602/db9ac2b0-3066-11e7-9edf-5d8eaba52a82.png)

**Comment by rvs16** [comment] 2017-05-08 05:36
Hey Hi,
Is the Touch issue solved..??

**Comment by lrinQVQ** [comment] 2017-05-08 07:38
@rvs16 hi~ I will testing in twrp 3.1.0,theoretically touch is work

**Comment by wolverine810** [comment] 2017-05-08 07:51
twrp 3.1 is available for this device??  I have 3.0 only where i can get 3.1??

**Comment by rvs16** [comment] 2017-05-08 08:25
Yeah please provide twrp 3.1.0 for q39.

**Comment by lrinQVQ** [comment] 2017-05-08 08:29
https://github.com/lrinQVQ/local_manifests
this is all for q39
we will testing before i fix gen dt.img bug,if twrp 3.1.0 work,i will upload to MEGA

**Comment by rvs16** [comment] 2017-05-15 03:45
Hello,
Is the ROM ready..??

**Comment by lrinQVQ** [comment] 2017-05-15 05:01
@rvs16 hi~ this is developing

**Comment by rvs16** [comment] 2017-05-18 16:37
Can u tell when will ROM get ready?
Been waiting very long for this ROM...

**Comment by lrinQVQ** [comment] 2017-05-18 19:45
@rvs16 hi～this device need hack kernel(finish) and maybe hack lk (bootloader) for new dtb, this very trouble，so～please wait

**Comment by wolverine810** [comment] 2017-06-02 05:14
Is twrp working now?

**Comment by lrinQVQ** [comment] 2017-06-03 05:54
@wolverine810 old dt.img + kernel + recovery rawimg is to big for q39 32m partition，so i hack lk(bootloader) ing

**Comment by wolverine810** [comment] 2017-06-04 16:39
Ok great!

**Comment by rvs16** [comment] 2017-06-07 07:15
did the developing stop..??

**Comment by lrinQVQ** [comment] 2017-06-07 08:14
hack lk(bootloader)ing

**Comment by lrinQVQ** [comment] 2017-06-07 10:16
this device is very trouble,boot partition size only 32m if we use old lk(bootloader) then twrp recovery rawimg 9m + kernel 25m(add prima f2fs) + dt,img 1m is so big for boot partition,and tcl's bootloader only support dt.img,so i have to hakc lk (bootloader)

**Comment by rvs16** [comment] 2017-06-08 04:31
Did u think of increasing boot partition size..
I think we can do that..!!!

**Comment by lrinQVQ** [comment] 2017-06-08 05:45
if do this... we need change to many partition

**Comment by rvs16** [comment] 2017-06-08 11:08
Can't we decrease data partition and increase that in boot partition

**Comment by lrinQVQ** [comment] 2017-06-08 12:39
https://github.com/lrinQVQ/android_qcom_display_panel
I only can hack lk(bootloader),else this's more trouble orz

**Comment by rvs16** [comment] 2017-06-08 15:19
ok.. But please do it fast...
Been waiting for very long...

**Comment by lrinQVQ** [comment] 2017-06-08 15:25
2333 yes,bootloader xd

**Comment by rajeevpmavoor** [comment] 2017-06-15 13:27
Hai lrinQVQ, how r u bro, thanks for ur hard work to develop CM 14 based ROM to TCL M3G. I am from India and I am using Swipe Elite Plus which is converted to M3G now. We all of us are eagerly waiting for ur great ROM . Can I ask about the status of the ROM ?. Hope it will be released soon . Thank you once again, have a great day.

**Comment by lrinQVQ** [comment] 2017-06-15 14:01
hi rajeevpmavoor ~
We will test new bootloader,if new bootloader work,twrp 3.1.0 is work,the aosp 7.1.1 lineage/cm 14.1 will work too.
hava a great day~
@rajeevpmavoor

**Comment by rajeevpmavoor** [comment] 2017-06-15 19:10
Dear lrinQVQ, wish u every success , keep it up

**Comment by lrinQVQ** [comment] 2017-06-15 21:17
thanks~ 
please see this:https://github.com/lrinQVQ/local_manifests/issues/1

**Comment by rajeevpmavoor** [comment] 2017-06-20 11:35
Hai lrinQVQ , any good news?

**Comment by lrinQVQ** [comment] 2017-06-21 00:34
QwQ,the lk can't boot,fixing

**Comment by rajeevpmavoor** [comment] 2017-06-21 01:29
OK bro

**Comment by rajeevpmavoor** [comment] 2017-07-11 08:48
Hai IrinQVQ how r u bro, any progress ?

**Comment by lrinQVQ** [comment] 2017-07-11 09:18
HI~, bootloader very not one's day,brain storm ing

**Comment by lrinQVQ** [comment] 2017-07-26 15:39
base android 5.1.1 XD

**Comment by rvs16** [comment] 2017-07-26 16:32
What does that mean..???

**Comment by lrinQVQ** [comment] 2017-07-26 16:40
I stop developing bootloader for m3g,because bootloader let too many people phone not work(now fix)
I have new plan for m3g,but i will developing 5.1.1 m3g First,
Maybe We need decrease data partition and increase that in boot partition,thank you~ @rvs16

**Comment by rvs16** [comment] 2017-07-26 16:41
hope to see that soon..!!!
Can you tell when will it be out..??

**Comment by lrinQVQ** [comment] 2017-07-26 16:46
The Kernel is work,so i only need developing Device Tree,and fix aosp-caf Android Build System,I will test twrp first
thanks for your support~
Have a great day~ @rvs16

**Comment by lrinQVQ** [comment] 2017-07-26 16:48
New branch is open:https://github.com/lrinQVQ/local_manifests/tree/LA.BR.1.1.2_rb1.9

**Comment by lrinQVQ** [comment] 2017-07-26 16:55
Good Night,See you tomorrow~(Time:00:55)

**Comment by lrinQVQ** [comment] 2017-07-28 06:45
now here

**Comment by imknown** [comment] 2017-07-28 06:56
:D

**Comment by rajeevpmavoor** [comment] 2017-08-06 02:54
Hai

**Comment by lrinQVQ** [comment] 2017-08-06 09:30
Hi～
Fix touch ing

**Comment by rajeevpmavoor** [comment] 2017-08-06 13:17
Great , wishes all the success in it , keep going.

**Comment by lrinQVQ** [comment] 2017-08-06 14:58
Thanks ~

**Comment by rvs16** [comment] 2017-08-10 04:11
Hey,..
I need your help...!!
My phone was bricked.. its not responding..
I was unable to get into recovery or download mode...

**Comment by rvs16** [comment] 2017-08-10 04:11
What should i do..??

**Comment by rvs16** [comment] 2017-08-10 04:47
the phone only responds when keep pressed vol- and power together..
the kernel boots and it shows symbol for ten seconds and then its gone...
no other combinations are working...
plz help...

**Comment by imknown** [comment] 2017-08-10 05:44
@rvs16 WHAT did you do...

**Comment by rvs16** [comment] 2017-08-10 05:52
I was flashing rom and it took too long like 30min..
so i tried to restart in between..
and  it din't start again

**Comment by rvs16** [comment] 2017-08-10 06:11
any idea what to do..??

**Comment by lrinQVQ** [comment] 2017-08-10 06:57
you need boot to 9006 first,shutdown your phone,then keep pressed vol- and Plug in USB
and then you need delete all phone partition,and shutdown again keep pressed vol- and Plug in USB,this will boot to 9008 auto ,then you can use QFIL to flash full rom @rvs16

**Comment by lrinQVQ** [comment] 2017-08-10 07:15
0.0 Do you have TG Or Twitter Or other

**Comment by rvs16** [comment] 2017-08-10 10:06
twitter: rvssandeep @rvsraj

**Comment by rvs16** [comment] 2017-08-10 10:11
when i keep vol- and power pressed pc shows mtp and only for 10 sec.. and then its gone no 9006..
plz tell how to repair.. i even cant get to recovery.. or any any other mode..

**Comment by rvs16** [comment] 2017-08-10 12:56
can someone provide twrp img file that works on this phone...
plz urgent..

**Comment by imknown** [comment] 2017-08-10 14:10
@rvs16 
- http://forum.xda-developers.com/general/device-reviews-and-information/umi-emax-mini-64bit-octa-core-fhd-4g-t3204602/page10#edit67211851

- http://community.umidigi.com/forum.php?mod=redirect&goto=findpost&ptid=2286&pid=22193&fromuid=139656

**Comment by rvs16** [comment] 2017-08-10 15:21
No links are working.. All files are removed..
Do you have the file... Can you upload it here..

**Comment by rvs16** [comment] 2017-08-10 17:55
Hey guys,
The problem is solved.. thanks for the support..

**Comment by lrinQVQ** [comment] 2017-08-10 18:02
congratulation～～((・∀・))

**Comment by lrinQVQ** [comment] 2017-08-10 18:07
XD I'm So Sorry,power = Plug in USB XD @rvs16

**Comment by rvs16** [comment] 2017-08-10 19:09
I ran into a different problem..
every thing ok but when i try to restore qcn it shows 
Checking for phone connection....
and fails.. any solution for this..??

**Comment by lrinQVQ** [comment] 2017-08-10 19:24
are you 9008 mode 0.0

**Comment by wolverine810** [comment] 2017-08-16 09:57
if nougat is not possible will u develop marshmallow here work done by ontherunvaro 
https://github.com/ontherunvaro/android_device_tcl_q39/tree/cm-13.0

**Comment by lrinQVQ** [comment] 2017-08-16 10:00
but the kernel touch driver must be work XD

**Comment by wolverine810** [comment] 2017-08-16 11:08
it says Builds, boots, unstable, several features not working in status here
https://github.com/ontherunvaro/android_device_tcl_q39/tree/cm-13.0
may be drivers are also working??

**Comment by lrinQVQ** [comment] 2017-08-16 11:51
But0.0 The Touch Driver in kernel,it's a dts node and a Modules device tree don't have driversXD

**Comment by kxerxess** [comment] 2017-08-20 15:48
Hey, just wanted to know if development for nougat or any other rom is on going or stopped? eagerly waiting. appreciate the effort.

**Comment by lrinQVQ** [comment] 2017-08-20 16:23
I'm vexed touch drivers ing QwQ

**Comment by rajeevpmavoor** [comment] 2017-09-14 12:33
I think forget about CM 14 , so sad.

**Comment by lrinQVQ** [comment] 2017-09-14 12:50
touch drivers ...XD

**Comment by wolverine810** [comment] 2017-09-14 14:14
Qualcomm didn't release drivers?

**Comment by wolverine810** [comment] 2017-09-14 14:14
For nougat*

**Comment by rajeevpmavoor** [comment] 2017-09-14 14:52
"( touch drivers ...XD ) " , what this means?

**Comment by lrinQVQ** [comment] 2017-09-14 15:06
touch drivers can't work... this is vendor private i try hack this but this is hard

**Comment by imknown** [comment] 2017-09-15 01:14
Lets give up the `Nougat`. Will the `Oreo Project Treble` save us?

**Comment by rajeevpmavoor** [comment] 2017-09-25 06:52
I think no hope

**Closed as completed** 2020-05-18 04:42 UTC
